FROM ubuntu:18.04

LABEL maintainer="Coen van den Munckhof" \
  org.label-schema.name="Server" \
  org.label-schema.description="SSH Rsync backup server for Synology NAS" \
  org.label-schema.url="https://github.com/coenm/Synology" \
  org.label-schema.vcs-url="https://github.com/coenm/Synology" \
  org.label-schema.vendor="CoenM" \
  org.label-schema.schema-version="1.0"


ENV REFRESHED_AT 2019-11-08
ENV SSH_USERNAME dockerbackup

RUN apt-get -yqq update && \
    apt-get -yqq install openssh-server && \
    apt-get -yqq install rsync 

RUN mkdir /var/run/sshd

#RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config

ADD sshd/fixed_sshd_config /etc/ssh/sshd_config

# https://stackoverflow.com/questions/27701930/add-user-to-docker-container
RUN useradd -ms /bin/bash ${SSH_USERNAME}

ENV BACKUP_DESTINATION /backup
VOLUME [ "/backup" ]

VOLUME [ "/tmp/.ssh/" ]

# https://stackoverflow.com/questions/36292317/why-set-visible-now-in-etc-profile
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# https://nickjanetakis.com/blog/docker-tip-56-volume-mounting-ssh-keys-into-a-docker-container
COPY entrypoint.sh /bin/docker-entrypoint.sh
RUN chmod +x /bin/docker-entrypoint.sh 

EXPOSE 22
ENTRYPOINT ["/bin/docker-entrypoint.sh"]
CMD ["/usr/sbin/sshd", "-D"]

# https://github.com/moby/moby/issues/6396
# http://www.inanzzz.com/index.php/post/qdil/creating-a-ssh-server-with-openssh-by-using-docker-compose-and-connecting-to-it-with-php

# docker exec -ti server /bin/bash
# docker run -d -p 22222:22 --name server --mount type=bind,source="/c/Users/coen/docker/ssh/",target="/tmp/.ssh/",readonly --rm coenm/server:v1.9
# docker run -d -p 22222:22 --name server --mount type=bind,source="/c/Users/coen/docker/ssh/",target="/tmp/.ssh/",readonly --mount type=bind,source="/c/Users/coen/docker/backup/",target="/backup/" --rm coenm/server:v1.10

# docker desktop
# docker run -d -p 22222:22 --name server --mount type=bind,source="D:/Docker/BackupServer/ssh/",target="/tmp/.ssh/",readonly --mount type=bind,source="D:/Docker/BackupServer/backup/",target="/backup/" --rm coenm/server:2.0
# docker run -d -p 22222:22 --name server --mount type=bind,source="/D/Docker/BackupServer/ssh/",target="/tmp/.ssh/",readonly --mount type=bind,source="/D/Docker/BackupServer/backup/",target="/backup/" --rm coenm/server:2.0


# docker run -ti --name ubuntu --mount type=bind,source="/D/Docker/UbuntuShare",target="/WindowsShare/" ubuntu:latest /bin/bash